kind: pipeline
type: docker
name: default

steps:
- name: npm install
  image: node:18.17.0
  commands:
  - npm install

# 开发环境阶段
dev:
  image: node:18.17.0
  environment:
    - development
  commands:
    - npm install
    - npm run dev

deploy:
  image: node:18.17.0
  environment:
    - production
  commands:
    - npm install --production
    - npm run prd
